dist: trusty
os: linux
language: java
jdk: openjdk14

#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

#script: "mvn cobertura:cobertura"
##script: rm -rf ~/.m2 ; mvn -U dependency:resolve-plugins

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

branches:
    only:
        - integration
